name: Build PHP 8.2 CLI Image
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:magento-php-82-cli"
          tags: ghcr.io/humanelement/magento-php:8.2-cli
