name: Build PHP 7.4 CLI Image
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    paths:
      - magento-php-74-cli/**
    tags:
      - force-build
      - force-build-7.4
permissions:
  contents: read
  packages: write
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to image repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:magento-php-74-cli"
          tags: ghcr.io/humanelement/magento-php:7.4-cli
